## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
app_cat = application_df.dtypes.index.tolist()
application_df[app_cat].nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
app_type_count = application_df['APPLICATION_TYPE'].value_counts()
app_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_count[app_type_count < 600].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
class_count = application_df['CLASSIFICATION'].value_counts()
class_count.head(20)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_count[class_count < 300].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_app_df = pd.get_dummies(application_df)
numeric_app_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = numeric_app_df["IS_SUCCESSFUL"]
X = numeric_app_df.drop(["IS_SUCCESSFUL"],axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 9
hidden_nodes_layer2 = 18

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 9)                 396

 dense_1 (Dense)             (None, 18)                180

 dense_2 (Dense)             (None, 1)                 19

=================================================================
Total params: 595
Trainable params: 595
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.6030 - accuracy: 0.6923
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5595 - accuracy: 0.7267
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5540 - accuracy: 0.7283
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7288
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5507 - accuracy: 0.7305
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7317
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7322
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7326
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7324
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7331
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7325
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7327
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5465 - accuracy: 0.7335
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7329
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5456 - accuracy: 0.7324
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7332
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7338
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7338
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7347
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7338
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7351
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7348
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7339
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7344
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7349
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7341
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7341
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7347
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7348
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7345
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7338
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7351
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7350
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7355
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7351
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7354
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7345
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7348
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7349
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7347
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7349
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7350
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7355
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7350
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7352
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7359
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7356
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7361
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7350
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7347
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7359
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7362
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7358
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7354
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7360
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7359
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7360
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7358
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7366
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7359
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7350
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7357
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7353
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7362
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7353
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7364
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7347
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7364
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7362
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7352
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7349
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7349
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7357
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7363
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7356
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7360
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7360
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7359
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7352
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7354
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7349
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7363
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7358
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7366
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7366
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7361
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7358
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7372
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7356
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7357
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7358
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7367
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7365
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7364
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7353
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7373
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7361
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7363
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7360
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7355

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5502 - accuracy: 0.7324 - 399ms/epoch - 1ms/step
Loss: 0.5502194762229919, Accuracy: 0.7323614954948425

In [17]:
# Export our model to HDF5 file
nn.save('Models/AlphabetSoupCharity.h5')

#Attempt 2

In [18]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 9
hidden_nodes_layer2 = 18
hidden_nodes_layer3 = 27

# nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 9)                 396

 dense_1 (Dense)             (None, 18)                180

 dense_2 (Dense)             (None, 1)                 19

 dense_3 (Dense)             (None, 9)                 18

 dense_4 (Dense)             (None, 18)                180

 dense_5 (Dense)             (None, 27)                513

 dense_6 (Dense)             (None, 1)                 28

=================================================================
Total params: 1,334
Trainable params: 1,334
Non-trainable params: 0
_________________________________________________________________

In [19]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [21]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5757 - accuracy: 0.7213
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7329
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7340
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7341
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7349
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7348
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7360
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7356
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7357
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7343
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7343
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7364
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7355
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7342
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7350
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7356
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7361
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5417 - accuracy: 0.7354
Epoch 19/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5415 - accuracy: 0.7357
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7367
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7354
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7359
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7360
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7363
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7360
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7365
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7350
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7340
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7360
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7362
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7369
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7358
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7369
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7353
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7371
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7366
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7348
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7377
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7358
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7365
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7363
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7371
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7370
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7361
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7366
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7371
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7365
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7358
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7350
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7355
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7364
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7375
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7367
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7360
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7359
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7365
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7360
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7352
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7361
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7365
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7369
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7364
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7352
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7360
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7373
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7362
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7373
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7370
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7372
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7372
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7363
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7370
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7369
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7367
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7376
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7355
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7358
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7368
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7367
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7356
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7360
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7357
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7366
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7373
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7360
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7373
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7377
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7355
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7368
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7370
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7361
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7371
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7366
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7375
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7374
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7359
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7364
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7364
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7367
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7355

In [22]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5525 - accuracy: 0.7263 - 427ms/epoch - 2ms/step
Loss: 0.5524578094482422, Accuracy: 0.7262973785400391

In [24]:
nn.save('Models/AlphabetSoupCharity2.h5')

Attempt **3**

In [25]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 8
hidden_nodes_layer3= 6

nn_model2 = tf.keras.models.Sequential()

# First hidden layer
nn_model2.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
             input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn_model2.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer2, activation="sigmoid"))

# Third hidden layer
nn_model2.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn_model2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_7 (Dense)             (None, 10)                440

 dense_8 (Dense)             (None, 8)                 88

 dense_9 (Dense)             (None, 6)                 54

 dense_10 (Dense)            (None, 1)                 7

=================================================================
Total params: 589
Trainable params: 589
Non-trainable params: 0
_________________________________________________________________

In [26]:
# Compile the model
nn_model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
# Train the model
fit_model2 = nn_model2.fit(X_train_scaled, y_train, epochs=30)

Epoch 1/30
804/804 [==============================] - 2s 1ms/step - loss: 0.6203 - accuracy: 0.6830
Epoch 2/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5724 - accuracy: 0.7285
Epoch 3/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5641 - accuracy: 0.7284
Epoch 4/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5582 - accuracy: 0.7308
Epoch 5/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5555 - accuracy: 0.7311
Epoch 6/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5543 - accuracy: 0.7304
Epoch 7/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5533 - accuracy: 0.7296
Epoch 8/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5527 - accuracy: 0.7313
Epoch 9/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5520 - accuracy: 0.7314
Epoch 10/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5517 - accuracy: 0.7316
Epoch 11/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7321
Epoch 12/30
804/804 [==============================] - 4s 4ms/step - loss: 0.5508 - accuracy: 0.7310
Epoch 13/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5504 - accuracy: 0.7319
Epoch 14/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7327
Epoch 15/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7326
Epoch 16/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7332
Epoch 17/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7326
Epoch 18/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5492 - accuracy: 0.7336
Epoch 19/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7332
Epoch 20/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5487 - accuracy: 0.7332
Epoch 21/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7325
Epoch 22/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7336
Epoch 23/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7344
Epoch 24/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7330
Epoch 25/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7331
Epoch 26/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7331
Epoch 27/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7336
Epoch 28/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7324
Epoch 29/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7338
Epoch 30/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7339

In [28]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5547 - accuracy: 0.7296 - 349ms/epoch - 1ms/step
Loss: 0.5547016263008118, Accuracy: 0.7295626997947693

In [29]:
nn.save('Models/AlphabetSoupCharity3.h5')